### ISSUE TITLE
Game considerations (kind of a summary of what we're making)

### ISSUE THREAD

**Issue by jhoak** [nanflasted/SouthPole#4]
Story of the game: Earth just had a global nuclear war. The entire southern hemisphere is frozen over and the northern hemisphere is one big lava ocean.
Someone is building spaceships in the south pole. Players must travel there to get onto the ships and escape the bad conditions on Earth.
----->An offline, single-player campaign might be worked out. Focus is currently on multiplayer mode.

Objective: Start players somewhere on the map with their own resources (i.e. money, dogs, items) and use moves + resources to get to South Pole as quickly as possible while acquiring additional resources and fighting/making deals with others along the way
Ideas: 1) goal is to survive + make it to SP
           2) resources on map are scarce!

Players and Characters:
-Character creation occurs before the game starts, so players can choose what they want their character to be good at.
-Roles can be chosen to augment certain abilities, i.e. doctors, chefs, crafters, etc.
-Each player has health and hunger attributes that have negative affects if they are low. Zero health means game over, while zero hunger lowers the player's health over time. Hunger automatically goes down over time (as in, the player gets hungrier).
-Each player has a maximum number of "action points" per day which dictates how many (and which) moves a player can make that day. This can be increased (temporarily, maybe permanently)
through items.
---> Action points can be spent on the following actions:
    Movement (the pulling power plays into how much a player can move)
    Interaction with other players (i.e. attacking, stealing, or trading)
    Using items
    Nothing (if the player chooses to end his/her turn early without using all of his/her points)

-All players have a radar which serves as a personal map, showing locations of nearby towns, resources and players. When turned on, it shows the player's location on other players' radars;
when turned off, this player is not visible on anyone else's radar.
-Players can converse with each other via communication devices, which (as part of the story) are part of the aforementioned radars. 

Spawning:
-Map is a square, the area that you can move in is a circle inscribed in the square (water surrounds the mainland) [()]
-Spawn on edge of circle (towns are also on edge of circle)
    *Note on towns: Towns MIGHT be located closer to the center of the circle, instead of just on the edge. These extra towns act as additional "pit stops" for players. We may decide later to scatter extra supplies around the land instead of towns, or have both.
-Start with money, food, and dogs. Players first go to towns to purchase additional dogs, food (+dog food) and other items.

Dogs: 
-These allow you to travel around the area. 
-They "wear off" as they get old, but they are also affected by hunger and health (can be killed!)
-Once dead they can act as food for the player. The player can optionally kill them for food, or trade them for other resources.
-Extra dogs can be stored to act as "backup tires" in case other dogs die.
-Dogs have attributes for durability and power. Durability determines how long until they wear off (maybe hunger, but definitely aging)
 and power determines the speed at which they can pull you and your stuff.
-Each dog's overall pulling power can be negatively affected by a lack of health/hunger or aging.
-The total speed of your sled is determined by the pulling power of your dogs as well as the weight of your stuff (remember to exclude these dogs' weights in the implementation).

Items: 
These can affect player and dog attributes as well as multiple other things in the game.
-Ideas for basic consumables: Food, dog food, energy bars (these replenish or add to max action points in a day), medicine or medicinal herbs
-Other items: Weapons (contribute to fighting ability, both with players and with BARBS) and tools (help with various tasks)

Misc:
Events can happen throughout the game that affect players, i.e. BARB ATTACKS and weather effects.
Random items (and possibly traps) can also be found.

**Comment by nanflasted** [comment]
Thank you

**Comment by WJLiddy** [comment]
Are we really having babs?

**Comment by nanflasted** [comment]
BABS PLS

**Comment by nanflasted** [comment]
**_# CLOSED????? :'(_**

> `

- little SNIFF

`

**_hey ted I edited ur comment :^)~~_**
-ted :^)
